import type { ComponentStatus } from "@/lib/component-status";

export type ComponentMeta = {
  name: string;
  title: string;
  description: string;
  status: ComponentStatus;
};

export const components: ComponentMeta[] = [
  {
    name: "accordion",
    title: "Accordion",
    description: "Glass disclosure list with calm, readable triggers.",
    status: "done",
  },
  {
    name: "alert",
    title: "Alert",
    description: "Toned alert banner with icon and description.",
    status: "done",
  },
  {
    name: "alert-dialog",
    title: "Alert Dialog",
    description: "Confirmation dialog with destructive action support.",
    status: "done",
  },
  {
    name: "aspect-ratio",
    title: "Aspect Ratio",
    description: "Maintains a consistent width-to-height ratio.",
    status: "unchanged",
  },
  {
    name: "avatar",
    title: "Avatar",
    description: "Profile image with fallback initials.",
    status: "done",
  },
  {
    name: "badge",
    title: "Badge",
    description: "Compact label with variant support.",
    status: "done",
  },
  {
    name: "breadcrumb",
    title: "Breadcrumb",
    description: "Navigation breadcrumb trail with separator.",
    status: "done",
  },
  {
    name: "button",
    title: "Button",
    description: "Sharp button system with balanced text.",
    status: "done",
  },
  {
    name: "button-group",
    title: "Button Group",
    description: "Group of connected buttons.",
    status: "done",
  },
  {
    name: "calendar",
    title: "Calendar",
    description: "Date selection calendar component.",
    status: "unchanged",
  },
  {
    name: "card",
    title: "Card",
    description: "Glass surface container with header and content.",
    status: "done",
  },
  {
    name: "carousel",
    title: "Carousel",
    description: "Scrollable content carousel with controls.",
    status: "done",
  },
  {
    name: "chart",
    title: "Chart",
    description: "Data visualization with Recharts.",
    status: "unchanged",
  },
  {
    name: "checkbox",
    title: "Checkbox",
    description: "Checkbox input with label.",
    status: "done",
  },
  {
    name: "collapsible",
    title: "Collapsible",
    description: "Expandable content section.",
    status: "unchanged",
  },
  {
    name: "combobox",
    title: "Combobox",
    description: "Searchable dropdown selection.",
    status: "done",
  },
  {
    name: "command",
    title: "Command",
    description: "Command palette with search.",
    status: "done",
  },
  {
    name: "context-menu",
    title: "Context Menu",
    description: "Right-click context menu.",
    status: "done",
  },
  {
    name: "data-table",
    title: "Data Table",
    description: "Full-featured data table with sorting and filtering.",
    status: "done",
  },
  {
    name: "date-picker",
    title: "Date Picker",
    description: "Date selection with popover calendar.",
    status: "done",
  },
  {
    name: "dialog",
    title: "Dialog",
    description: "Zero-radius modal with glass surface.",
    status: "done",
  },
  {
    name: "drawer",
    title: "Drawer",
    description: "Slide-out panel from screen edge.",
    status: "done",
  },
  {
    name: "dropdown-menu",
    title: "Dropdown Menu",
    description: "Dropdown menu with items and sub-menus.",
    status: "done",
  },
  {
    name: "empty",
    title: "Empty",
    description: "Empty state placeholder with icon and action.",
    status: "unchanged",
  },
  {
    name: "field",
    title: "Field",
    description: "Form field wrapper with label and description.",
    status: "unchanged",
  },
  {
    name: "form",
    title: "Form",
    description: "Form with validation and error handling.",
    status: "unchanged",
  },
  {
    name: "hover-card",
    title: "Hover Card",
    description: "Popover card shown on hover.",
    status: "done",
  },
  { name: "input", title: "Input", description: "Text input field.", status: "done" },
  {
    name: "input-group",
    title: "Input Group",
    description: "Input with prefix/suffix addons.",
    status: "done",
  },
  {
    name: "input-otp",
    title: "Input OTP",
    description: "One-time password input with slots.",
    status: "done",
  },
  {
    name: "item",
    title: "Item",
    description: "List item with icon and description.",
    status: "done",
  },
  { name: "kbd", title: "Kbd", description: "Keyboard shortcut display.", status: "done" },
  { name: "label", title: "Label", description: "Form label element.", status: "done" },
  {
    name: "menubar",
    title: "Menubar",
    description: "Horizontal menu bar with dropdowns.",
    status: "done",
  },
  {
    name: "navigation-menu",
    title: "Navigation Menu",
    description: "Horizontal navigation with dropdowns.",
    status: "done",
  },
  {
    name: "pagination",
    title: "Pagination",
    description: "Page navigation controls.",
    status: "done",
  },
  { name: "popover", title: "Popover", description: "Floating content panel.", status: "done" },
  { name: "progress", title: "Progress", description: "Progress bar indicator.", status: "done" },
  {
    name: "radio-group",
    title: "Radio Group",
    description: "Radio button group selection.",
    status: "done",
  },
  {
    name: "resizable",
    title: "Resizable",
    description: "Resizable panel layout.",
    status: "unchanged",
  },
  {
    name: "scroll-area",
    title: "Scroll Area",
    description: "Custom scrollbar container.",
    status: "unchanged",
  },
  { name: "select", title: "Select", description: "Dropdown select menu.", status: "done" },
  { name: "separator", title: "Separator", description: "Visual divider line.", status: "done" },
  { name: "sheet", title: "Sheet", description: "Side panel overlay.", status: "done" },
  {
    name: "skeleton",
    title: "Skeleton",
    description: "Loading placeholder animation.",
    status: "done",
  },
  { name: "slider", title: "Slider", description: "Range slider input.", status: "done" },
  { name: "sonner", title: "Sonner", description: "Toast notification system.", status: "done" },
  { name: "spinner", title: "Spinner", description: "Loading spinner indicator.", status: "done" },
  { name: "switch", title: "Switch", description: "Toggle switch control.", status: "done" },
  { name: "table", title: "Table", description: "Data table layout.", status: "unchanged" },
  { name: "tabs", title: "Tabs", description: "Tabbed content panels.", status: "done" },
  { name: "textarea", title: "Textarea", description: "Multi-line text input.", status: "done" },
  { name: "toggle", title: "Toggle", description: "Toggle button control.", status: "done" },
  {
    name: "toggle-group",
    title: "Toggle Group",
    description: "Group of toggle buttons.",
    status: "done",
  },
  { name: "tooltip", title: "Tooltip", description: "Hover tooltip popup.", status: "done" },
  { name: "typography", title: "Typography", description: "Text variant system.", status: "done" },
  {
    name: "sidebar",
    title: "Sidebar",
    description:
      "Navigation shell with squared rails, readable labels, and an off-canvas mobile experience.",
    status: "done",
  },
  {
    name: "toast",
    title: "Toast",
    description: "Toast notifications powered by Sonner with Omni glass styling.",
    status: "done",
  },
  {
    name: "react-hook-form",
    title: "React Hook Form",
    description: "Form helpers connecting Omni field primitives to React Hook Form.",
    status: "done",
  },
];
