packages:
  - "."
  - "apps/*"

catalogMode: prefer

catalog:
  "@corvu/calendar": 0.1.2
  "@types/node": ^24
  "@unovis/solid": 1.6.1
  cva: 1.0.0-beta.4
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.2.3
  vite-plus: 0.2.3

overrides:
  vite: "catalog:"
  "@types/react": "19.1.2"
  "@types/react-dom": "19.1.2"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  esbuild: true
  maplibre-gl: false
  sharp: true
